name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 21]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: Europe/Paris
      - name: System info
        run: |
          echo "node"
          node -v
          echo "npm"
          npm -v
          echo "yarn"
          yarn -v
      - name: Install modules
        run: yarn install
      - name: Run lint tasks
        run: |
          yarn lint
          yarn prettier
      - name: Run tests
        run: yarn test
